### ISSUE TITLE
Error when kafka connect is not configured

### ISSUE THREAD

**Issue by yannick-roeder** [bakdata/streams-explorer#231]
When deploying streams explorer without Kafka Connect I encounter the following error after opening the UI:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/./streams_explorer/api/routes/metrics.py", line 18, in get_metrics
    return await streams_explorer.get_metrics()
  File "/app/./streams_explorer/streams_explorer.py", line 73, in get_metrics
    return await self.data_flow.get_metrics()
  File "/app/./streams_explorer/core/services/dataflow_graph.py", line 169, in get_metrics
    if self.metric_provider is not None:
AttributeError: 'DataFlowGraph' object has no attribute 'metric_provider'
```

Receiving a proper error by setting `must_exist=True`  [here](
https://github.com/bakdata/streams-explorer/blob/main/backend/streams_explorer/core/config.py#L44) and documenting it inside the README would already help. Maybe we can even allow the usage of streams explorer without Kafka Connect.

Additionally we should update the helm commands inside the documentation, so that they work with the newest helm version

**Comment by disrupted** [comment]
Thanks for the detailed report! This is certainly a bug. It's not directly related to Kafka Connect, but rather when Prometheus (the metrics provider) is not configured.

This is already fixed it on the development branch (https://github.com/bakdata/streams-explorer/tree/feat/v2/kubernetes-watch), but in the meantime I will push a separate fix to main.
