### ISSUE TITLE
Error loading webpage: Failed to fetch: 500

### ISSUE THREAD

**Issue by philipp94831** [bakdata/streams-explorer#42]
```
2021-02-03 16:36:13.848 | DEBUG    | streams_explorer.core.services.metric_providers:refresh_data:100 - Pulling metrics from Prometheus
10.0.1.141:30050 - "GET /api/metrics HTTP/1.1" 500
[2021-02-03 16:36:21 +0000] [7] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/streams_explorer/api/routes/metrics.py", line 18, in metrics
    return streams_explorer.get_metrics()
  File "/app/streams_explorer/streams_explorer.py", line 62, in get_metrics
    return self.data_flow.get_metrics()
  File "/app/streams_explorer/core/services/dataflow_graph.py", line 92, in get_metrics
    return self.metrics_provider.get()
  File "/app/streams_explorer/core/services/metric_providers.py", line 80, in get
    self.update()
  File "/app/streams_explorer/core/services/metric_providers.py", line 61, in update
    self.metrics = [
  File "/app/streams_explorer/core/services/metric_providers.py", line 65, in <listcomp>
    self.get_consumer_group(node_id, node)
  File "/app/streams_explorer/core/services/metric_providers.py", line 54, in get_consumer_group
    node_type: NodeTypesEnum = node["node_type"]
KeyError: 'node_type'
```

I deleted a connector and the respective dead letter topic and consumer group, maybe it is related

**Comment by disrupted** [comment]
Fixed in #36
